name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - "28.1"
          - "29.1"
          - "30.2"
          - snapshot

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Emacs
        uses: d12frosted/setup-emacs@v1
        with:
          version: ${{ matrix.emacs_version }}

      - name: Setup Eldev
        uses: emacs-eldev/setup-eldev@v1

      - name: Install dependencies
        run: eldev prepare

      - name: Lint
        run: eldev lint

      - name: Compile
        run: eldev compile --warnings-as-errors

      - name: Test
        run: eldev test
